### PR TITLE
Fix a few minor deprecations

### PR DESCRIPTION
**Pull request by sedabull**
Just a few minor things the deprecation cop alerted me to, this is an awesome package BTW! I'm glad it's finally working :smile:

### CODE REVIEW

**Comment by mark-hahn** [comment]
Thank you very much!

**Comment by mark-hahn** [comment]
>  I'm glad it's finally working :smile:

Me too. There are still a couple of serious bugs caused by the `webview` tag again but hopefully they will be fixed faster than the big one before.

Back to working on features ...

**Comment by sedabull** [comment]
Sounds good to me! I wanted to ask you something, actually. Are you familiar with the new service provider API? I was thinking about playing with it a little, and I was going to use `web-browser` as a guinea pig. Would you be open to a PR that adds a service dependency to this package if I can come up with something really cool?

**Comment by mark-hahn** [comment]
>  Would you be open to a PR that adds a service dependency to this package

Yes!  

I assume you mean that `web-browser` would be a service that other packages would use.  I've got a lot of ideas for things that need to call the browser.  For example, a context help that would bring up the actual help web pages for selected words.

**Comment by sedabull** [comment]
Actually I meant `web-browser` would depend on a service I provide from `quantum-shell`. You see, I've realized the the command line is a very comfortable and familiar interface for a lot of the *hackers* who are *hacking* on the *hackable* text editor :grin: and it just so happens that my package is a command line interface that runs in atom, much like [thedaniel/terminal-panel](http://github.com/thedaniel/terminal-panel). However, my focus has been more on builtins and I quickly realized that an `atom` builtin that sends commands directly to atom would be awesome. And infact, it is! I've got it mostly working and it should be available in the next release. But after I got that working, I realized that it would be *really* awesome if individual packages could accept command-line input from quantum-shell (instead of the traditional key-bindings). Basically, when all is said and done, my package `quantum-shell` would provide a service that your package `web-browser` would subscribe to. I'd write the code for your package that turns `web-browser` into a command line tool. Meaning a user could pull up `quantum-shell` type something like:
```
web-browser open atom.io
```
and your package would handle the rest. Please keep in mind though, that this is all still contained entirely inside my head, and it would probably be a week or two before I had anything worth looking at.

**Comment by mark-hahn** [comment]
The end result of your idea is the same as mine.   Your example `web-browser open atom.io` would do what I was talking about.  It would be an external package talking to mine to bring up a page.  This would work with either package being the service and the other one the client.  

Having said that, I would welcome a PR for my package to register as a client.  Maybe I could learn from your work and also provide my package as a service.

We just have to make sure we don't end up with each package registering with the other in an infinite loop.  (grin)

**Comment by sedabull** [comment]
> We just have to make sure we don't end up with each package registering with the other in an infinite loop. (grin)

Indeed :grin:, however it the interest of openness, I should tell you that I have less-than-technical reasons for wanting `quantum-shell` to be the service provider. I would like to eventually create a many-to-one relationship with as many different packages as possible. If this happened, in my readme, I would point to `web-browser` as the canonical "how-to-turn-my-package-into-a-command-line-tool" example, in the hopes that other package authors would be inspired to subscribe to this hypothetical service. Plus, I wouldn't mind piggybacking all of the exposure `web-browser` has been receiving recently...isn't it always better to "stand on the shoulder of giants"? :smile:

**Comment by mark-hahn** [comment]
> in the hopes that other package authors would be inspired to subscribe to this hypothetical service. 

It occurred to me that you aren't dependent on the other package authors.  If it is easy to register and provide a service as I think, you could do PRs for a lot of other packages.  I don't see why any would reject your PR as it adds another feature.

It will be really easy in my package.  One simple call with a URL argument will open any page.  This assumes that the service API is easy to use. 

I haven't looked at the service API.  Will it automatically install your package when I register for your service?  If so you'll get a lot of installs from that.

**Comment by sedabull** [comment]
> It will be really easy in my package.

yes, that's why I was hoping you'd be okay with it. I don't have any experience with the services API, and the simpler the implementation, the more I can focus on learning what is needed to make something like this work.



> Will it automatically install your package when I register for your service?

I am unsure, but I certainly hope so!

**Pull request merged**
