### PR TITLE
pretty auto-reloading state

### PR DESCRIPTION
**Pull request by braver**
RE: https://github.com/mark-hahn/web-browser/pull/10#issuecomment-73399139

How about this?

screen shot 2015-02-08 at 12 08 13
screen shot 2015-02-08 at 12 08 27
screen shot 2015-02-08 at 12 08 35

### CODE REVIEW

**Comment by mark-hahn** [comment]
Thanks.  I thought it would be rude to ask so I just hinted.  (grin)

I think I have to see this in action before commenting.  I'll merge this now.

**Comment by mark-hahn** [comment]
Your screen caps show a doc icon on the right of the favicon.  What is that?

I know beggars can't be the choosers, but here are some comments.  All are optional and I'll go with whatever you suggest.

- It bugs me a bit that it overlaps the favicon.
- Could it surround the favicon and be the spinning activity indicator?  
  - Only on live tabs.
  - it could happen only on the auto-reloads.  I could put a class in for autos
- Or, maybe what you have now could be in the far upper left with the rest pushed to the right?

**Comment by mark-hahn** [comment]
I have a stupid question.  How can I try out a PR without closing the PR?  I need to do the merge to download it right?

**Comment by braver** [comment]
> Your screen caps show a doc icon on the right of the favicon. What is that?

That icon's from the file-icons package. It's kinda pushy about putting icons everywhere.

> I know beggars can't be the choosers, but here are some comments. 

Sure you can, it's your package. And no worries, I enjoy this :+1: 

> It bugs me a bit that it overlaps the favicon.

I agree. I tried to make that work well, but the colors clash and make it hard to read. 

> Could it surround the favicon and be the spinning activity indicator?

Err... ;)

> Only on live tabs.

I'm selecting the `.tab.live` right now. Is that correct?

> it could happen only on the auto-reloads. I could put a class in for autos

It would be nice to show something when it's processing. I'm still kinda fuzzy about how this thing work, I plan to put some more time on it during work next week.

> Or, maybe what you have now could be in the far upper left with the rest pushed to the right?

Actually, I think this is best. I'll try to take out the file-icons icon, and push everything aside. Overlapping sucks.

> Edit: On second thought the surrounding idea is tacky.

I think I agree ;)

> How can I try out a PR without closing the PR? I need to do the merge to download it right?

I don't know actually. Git can do pretty much everything, but over two years into it I still need guides for pretty much everything beyond the basics. Perhaps you can use the command line to pull a pr into a branch? I think you can add my fork as a remote using `git remote add downstream https://github.com/braver/web-browser.git`. Then you should be able to access my branches and commits and pull them into any of your branches.

**Comment by braver** [comment]
screen shot 2015-02-08 at 21 20 35
screen shot 2015-02-08 at 21 15 17
screen shot 2015-02-08 at 21 15 33

**Comment by braver** [comment]
Hmm, apparently new commits also don't come through if you close this. Anyway: https://github.com/braver/web-browser/commit/612f1bb5ad212560cecf46111bffb511e61d4983

**Comment by mark-hahn** [comment]
>  I'll try to take out the file-icons icon

That's kind of high priority.  It should be a PR to the package because it's a bug.  There shouldn't be a file icon if there is no file.  They can just do a `if item instanceof TextEditor`.

>  new commits also don't come through if you close this. 

That makes sense.  I'll ask on the forum how to do this.  @leedohm will know.

Thanks again.

**Comment by mark-hahn** [comment]
FYI:  Here is how to test a PR without closing it ... https://help.github.com/articles/checking-out-pull-requests-locally/

It is hard to do.  This seems like a missing functionality which you don't see often in github.

**Comment by braver** [comment]
Yeah, feels like that should've been easier.

Anyway, I think I fixed the file-icons thing: https://github.com/DanBrooker/file-icons/pull/113

**Pull request merged**
